 version: '3.3'
 services:
    app:
        container_name: app
        image: app
        build: ./
        depends_on:
            - mypostgres
        network_mode: "host"
    mypostgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=postgres
            - POSTGRES_DB=multiplex
        volumes:
            - db-data:/var/lib/postgresql/data
        network_mode: "host"

 volumes:
  db-data:
